data_ingestion:
  test_size: 0.201

model_building:
  ngram_range: [1, 3]
  max_features: 10000
  penalty: "l1"
  C: 2.262
  solver: "liblinear"
  max_iter: 352
  # class_weight: "balanced"
  # multi_class: "auto"
  # random_state: 42



